fail_fast: true

repos:

  - repo: https://github.com/psf/black
    rev: '23.3.0'
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.265'
    hooks:
      - id: ruff
        exclude: "test_[a-zA-Z0-9]+.py"
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.2.0'
    hooks:
      - id: mypy
        additional_dependencies: [types-requests==2.28.11.8]