name: Tests

on:
  workflow_call:
  push:
    branches-ignore:
      - main
      - master
      - dev
  pull_request:
    branches:
      - main
      - master
      - dev

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - uses: pre-commit/action@v3.0.0
  tests:
    needs: pre-commit
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      #----------------------------------------------
      # Check-out repo
      #----------------------------------------------
      - name: Checkout
        uses: actions/checkout@v3
      #----------------------------------------------
      # Set-up python
      #----------------------------------------------
      - name: Set up Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      #----------------------------------------------
      # Install poetry
      #----------------------------------------------
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
      #----------------------------------------------
      # Configure poetry and set up a venv
      #----------------------------------------------
      - name: Setup a local virtual environment (if no poetry.toml file)
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      #----------------------------------------------
      # Cache the venv
      #----------------------------------------------
      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      #----------------------------------------------
      # Install the package
      #----------------------------------------------
      - name: Install preadator
        run: poetry install --no-interaction
      #----------------------------------------------
      # Run test suite
      #----------------------------------------------
      - name: Run tests
        run: |
          poetry run pytest -v
      - name: Run tests in debug mode
        env:
          PREADATOR_DEBUG: 1
        run: |
          poetry run pytest -v
